set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv32)

set(RISCV_TOOLCHAIN_PREFIX riscv-none-elf- CACHE STRING "RISC-V GCC prefix")

set(CMAKE_C_COMPILER ${RISCV_TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_COMPILER ${RISCV_TOOLCHAIN_PREFIX}gcc)
set(CMAKE_OBJCOPY ${RISCV_TOOLCHAIN_PREFIX}objcopy)
set(CMAKE_SIZE ${RISCV_TOOLCHAIN_PREFIX}size)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
